services:
  mysql-product:
    image: mysql:latest
    restart: always
    container_name: mysql-product
    hostname: "mysql-product"
    environment:
      MYSQL_DATABASE: 'productdb'
      MYSQL_USER: 'productuser_mysql'
      MYSQL_PASSWORD: 'mSq@2024*PtEc'
      MYSQL_ROOT_PASSWORD: 'mSqR@@t*2024p@s'
    ports:
      - '3307:3307'
    networks:
      - my_network


  msproduct:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql-product
    hostname: "ms-product"
    environment:
      MYSQL_HOSTNAME: mysql-product
      MYSQL_PORT: 3307
    ports:
      - 8081:8081
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
    external: true